/**
 * Shared Prisma select constants for financial transactions.
 * Used by: getFinanceTransactionById, reverseFinanceTransaction, CRUD detail returns.
 *
 * Typed via `satisfies` to ensure compile-time errors for non-existent fields.
 */
import { Prisma } from '@prisma/client';

const TRANSACTION_SUMMARY_SELECT = {
  id: true,
  description: true,
  transaction_type: true,
  status: true,
  transaction_date: true,
  gross_amount_cents: true,
  net_amount_cents: true,
} satisfies Prisma.financial_transactionsSelect;

export const FINANCE_TRANSACTION_DETAIL_SELECT = {
  // Scalar fields
  id: true,
  external_reference: true,
  provider: true,
  provider_event_id: true,
  source_type: true,
  source_id: true,
  origin_type: true,
  origin_id: true,
  account_id: true,
  counterparty_account_id: true,
  category_id: true,
  cost_center_id: true,
  transfer_group_id: true,
  direction: true,
  transaction_type: true,
  status: true,
  payment_method: true,
  recognition_policy: true,
  competence_date: true,
  transaction_date: true,
  due_date: true,
  settlement_date: true,
  gross_amount_cents: true,
  fee_amount_cents: true,
  discount_amount_cents: true,
  retention_amount_cents: true,
  net_amount_cents: true,
  transfer_amount_cents: true,
  reversal_of_id: true,
  canceled_reason: true,
  canceled_at: true,
  description: true,
  memo: true,
  metadata: true,
  idempotency_key: true,
  created_by_admin_id: true,
  approved_by_admin_id: true,
  responsible_admin_id: true,
  created_at: true,
  updated_at: true,

  // Relations
  account: { select: { id: true, code: true, name: true, type: true, is_active: true } },
  counterparty_account: { select: { id: true, code: true, name: true, type: true, is_active: true } },
  category: { select: { id: true, code: true, name: true, kind: true, is_active: true, is_postable: true } },
  cost_center: { select: { id: true, code: true, name: true, type: true, is_active: true } },
  reversal_of: { select: TRANSACTION_SUMMARY_SELECT },
  reversals: {
    select: TRANSACTION_SUMMARY_SELECT,
    orderBy: [{ transaction_date: 'desc' as const }, { created_at: 'desc' as const }],
  },
  allocations: {
    select: {
      id: true,
      transaction_id: true,
      category_id: true,
      cost_center_id: true,
      amount_cents: true,
      allocation_type: true,
      description: true,
      metadata: true,
      created_at: true,
      updated_at: true,
      created_by_admin: { select: { id: true, name: true, role: true } },
      category: { select: { id: true, code: true, name: true, kind: true, is_active: true, is_postable: true } },
      cost_center: { select: { id: true, code: true, name: true, type: true, is_active: true } },
    },
    orderBy: [{ created_at: 'asc' as const }, { id: 'asc' as const }],
  },
  outgoing_links: {
    select: {
      id: true,
      transaction_id: true,
      linked_transaction_id: true,
      link_type: true,
      amount_cents: true,
      metadata: true,
      created_at: true,
      updated_at: true,
      created_by_admin: { select: { id: true, name: true, role: true } },
      linked_transaction: { select: TRANSACTION_SUMMARY_SELECT },
    },
    orderBy: [{ created_at: 'asc' as const }, { id: 'asc' as const }],
  },
  incoming_links: {
    select: {
      id: true,
      transaction_id: true,
      linked_transaction_id: true,
      link_type: true,
      amount_cents: true,
      metadata: true,
      created_at: true,
      updated_at: true,
      created_by_admin: { select: { id: true, name: true, role: true } },
      transaction: { select: TRANSACTION_SUMMARY_SELECT },
    },
    orderBy: [{ created_at: 'asc' as const }, { id: 'asc' as const }],
  },
  created_by_admin: { select: { id: true, name: true, role: true } },
  approved_by_admin: { select: { id: true, name: true, role: true } },
  responsible_admin: { select: { id: true, name: true, role: true } },
} satisfies Prisma.financial_transactionsSelect;
